---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: conjur
  namespace: cyberark
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: conjur-authenticator-role-binding-cyberark
subjects:
  - kind: ServiceAccount
    name: conjur
    namespace: cyberark
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: conjur-authenticator-cyberark
