---
apiVersion: v1
kind: Service
metadata:
  name: conjur-follower
  labels:
    app: conjur-follower
spec:
  ports:
  - port: 443
    name: https
  selector:
    app: conjur-follower
  type: LoadBalancer
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: conjur-follower
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: conjur-follower
        name: conjur-follower
        role: follower
    spec:
      serviceAccountName: conjur-cluster
      hostAliases:
      - ip: "192.168.99.100"
        hostnames:
        - "conjur-master"
      volumes:
      - name: seedfile
        emptyDir:
          medium: Memory
      - name: conjur-token
        emptyDir:
          medium: Memory

      initContainers:
      - name: authenticator
        image: 172.30.1.1:5000/conjur/seed-fetcher:conjur
        imagePullPolicy: 
        env:
          - name: CONJUR_SEED_FILE_URL
            value: https://conjur-master:30443/configuration/dev/seed/follower
          - name: SEEDFILE_DIR
            value: /tmp/seedfile
          - name: FOLLOWER_HOSTNAME
            value: conjur-follower # this should be the same value as the service name
          - name: AUTHENTICATOR_ID
            value: dev1
          - name: CONJUR_ACCOUNT
            value: dev
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: server-certificate
                key: ssl-certificate

          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_AUTHN_LOGIN
            value: "host/conjur/authn-k8s/dev1/apps/conjur/service_account/conjur-cluster"
        volumeMounts:
          - name: seedfile
            mountPath: /tmp/seedfile
          - name: conjur-token
            mountPath: /run/conjur

      containers:
      - name: conjur-appliance
        command: ["/tmp/seedfile/start-follower.sh"]
        image: 172.30.1.1:5000/conjur/conjur-appliance:conjur
        imagePullPolicy: 
        env:
          - name: CONJUR_MASTER_PORT
            value: "30443"
          - name: CONJUR_AUTHENTICATORS
            value: authn-k8s/dev1
          - name: SEEDFILE_DIR
            value: /tmp/seedfile
        resources:
          requests:
            cpu: "1"
            memory: 4Gi
          limits:
            cpu: "1"
            memory: 4Gi
        ports:
        - containerPort: 443
          name: https
        - containerPort: 5432
          name: pg-main
        - containerPort: 1999
          name: pg-audit
        volumeMounts:
          - name: seedfile
            mountPath: /tmp/seedfile
            readOnly: true
