#!/bin/bash
set -euo pipefail

source ../config/cluster.config
source ../config/$PLATFORM.config

oc login -u $CLUSTER_ADMIN_USERNAME

./0_check_dependencies.sh
./stop
./1_prepare_conjur_namespace.sh
./2_init_follower_authn.sh

if $CONJUR_FOLLOWERS_IN_CLUSTER; then
  $CLI login -u $FOLLOWER_ADMIN_USERNAME
  ./3_prepare_docker_images.sh
  ./4_deploy_conjur_followers.sh
  ./_update_follower_cert.sh # regenerates follower cert w/ OC Route SAN added
fi
