#!/bin/bash 

source ../config/cluster.config
source ../config/openshift.config
source ../config/utils.sh

oc login -u $CLUSTER_ADMIN_USERNAME
set_namespace $FOLLOWER_NAMESPACE_NAME

announce "Deleting Conjur deployments"

echo "Deleting Follower pods."
$CLI delete dc/conjur-follower --force=true
$CLI delete svc/conjur-follower --force=true

echo "Deleting server-certificate config map."
$CLI delete --ignore-not-found cm server-certificate 

echo "Deleting Route to Follower service."
$CLI delete route conjur-follower --force=true

echo "Deleting cluster role."
$CLI delete --ignore-not-found clusterrole conjur-authenticator-$FOLLOWER_NAMESPACE_NAME

echo "Waiting for Conjur pods to terminate..."
while [[ "$($CLI get pods -l app=conjur-follower 2>&1)" != "No resources found." ]]; do
  echo -n '.'
  sleep 3
done 
echo

echo "All deployments deleted."
