version: '2'
services:

  conjur:
    image: $CONJUR_APPLIANCE_IMAGE
    container_name: $CONJUR_MASTER_CONTAINER_NAME
    labels:
      role: "conjur_node"
    ports:
      - "0.0.0.0:443:$CONJUR_MASTER_PORT"
#    volumes:
#      - ./log:/var/log/conjur   # uncomment to export conjur audit log
#      - ./log:/var/log/nginx    # uncomment to export nginx audit log
    security_opt:
      - seccomp:unconfined
    restart: always

# The CLI container is used to execute Conjur commands. As the CLI is the
# admin UI for Conjur, this affords a way to control access to it.
  cli:
    image: $CLI_IMAGE_NAME
    container_name: $CLI_CONTAINER_NAME
    hostname: $CLI_CONTAINER_NAME
    environment:
      CONJUR_ACCOUNT: $CONJUR_ACCOUNT
      CONJUR_APPLIANCE_URL: $CONJUR_APPLIANCE_URL
    extra_hosts:
      - "$CONJUR_MASTER_HOST_NAME:$CONJUR_MASTER_HOST_IP"
    entrypoint: sleep
    command: infinity
    restart: always
