#!/bin/bash
set -euo pipefail

source ../config/cluster.config
source ../config/$PLATFORM.config
source ../config/utils.sh

$CLI login -u $CLUSTER_ADMIN_USERNAME

./0_check_dependencies.sh
./stop
./1_create_test_app_namespace.sh

$CLI login -u $DEVELOPER_USERNAME

./2_build_and_push_containers.sh
./3_load_policies.sh
./4_deploy_test_app.sh
./5_verify_authentication.sh
