#!/bin/bash
set -euo pipefail

./0_check_dependencies.sh
./stop
./1_create_test_app_namespace.sh
./2_build_and_push_containers.sh
./3_load_policies.sh
./4_deploy_test_app.sh
./5_verify_authentication.sh
