#!/bin/bash

source ../config/cluster.config
source ../config/openshift.config
source ../config/utils.sh

$CLI login -u $CLUSTER_ADMIN_USERNAME
set_namespace $TEST_APP_NAMESPACE_NAME

announce "Deleting image pull secret."
$CLI delete --ignore-not-found secrets dockerpullsecret

announce "Deleting test app/sidecar deployment."
$CLI delete dc/test-app-summon-sidecar
$CLI delete dc/test-app-summon-init

$CLI delete rolebinding test-app-conjur-authenticator-role-binding

echo "Waiting for pods to terminate"
until [[ "$($CLI get pods 2>&1)" == "No resources found." ]]; do
  sleep 4
  echo -n '.'
done
echo

echo "Test app deleted."
