---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: conjur
  namespace: {{ FOLLOWER_NAMESPACE_NAME }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: conjur-authenticator-role-binding-{{ FOLLOWER_NAMESPACE_NAME }}
subjects:
  - kind: ServiceAccount
    name: conjur
    namespace: {{ FOLLOWER_NAMESPACE_NAME }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: conjur-authenticator-{{ FOLLOWER_NAMESPACE_NAME }}
