---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: conjur-cli
  labels:
    app: conjur-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conjur-cli
  template:
    metadata:
      name: conjur-cli
      labels:
        app: conjur-cli
    spec:
      serviceAccountName: conjur-cluster
      tolerations:
      - key: "{{ CONJUR_MASTER_TAINT }}"
        operator: "Equal"
        value: "{{ CONJUR_MASTER_TAINT }}"
      containers:
      - name: conjur-cli
        image: {{ DOCKER_IMAGE }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        command: ["sleep"]
        args: ["infinity"]
      imagePullSecrets:
        - name: dockerpullsecret
