---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oc-test-app-summon-init
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: test-app-summon-init
  name: test-app-summon-init
spec:
  replicas: 1
  selector:
    app: test-app-summon-init
  template:
    metadata:
      labels:
        app: test-app-summon-init
    spec:
      serviceAccountName: oc-test-app-summon-init
      tolerations:
      - key: "{{ CONJUR_APP_TAINT }}"
        operator: "Equal"
        value: "{{ CONJUR_APP_TAINT }}"

      # Use hostAliases to bypass DNS
      hostAliases:
      - ip: "{{ CONJUR_MASTER_HOST_IP }}"
        hostnames:
        - "{{ CONJUR_MASTER_HOST_NAME }}"

      containers:

      # Application container
      - image: {{ TEST_APP_DOCKER_IMAGE }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        name: test-app
        env:

        # values from Conjur config map
          - name: CONJUR_APPLIANCE_URL
            valueFrom:
              configMapKeyRef:
                name: {{ CONFIG_MAP_NAME }}
                key: conjur-follower-url
          - name: CONJUR_ACCOUNT
            valueFrom:
              configMapKeyRef:
                name: {{ CONFIG_MAP_NAME }}
                key: conjur-account
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: {{ CONFIG_MAP_NAME }}
                key: follower-certificate
          - name: CONJUR_AUTHN_TOKEN_FILE
            valueFrom:
              configMapKeyRef:
                name: {{ CONFIG_MAP_NAME }}
                key: conjur-authn-token-file
          - name: CONJUR_VERSION
            valueFrom:
              configMapKeyRef:
                name: {{ CONFIG_MAP_NAME }}
                key: conjur-version

        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
            readOnly: true

      initContainers:

      # Authenticator client container
      - image: {{ AUTHENTICATOR_CLIENT_IMAGE }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        name: authenticator
        env:

        # hardcoded values
          - name: CONTAINER_MODE
            value: init

        # values from cluster metadata
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP

        # values from Conjur config map
          - name: CONJUR_VERSION
            valueFrom:
              configMapKeyRef:
                name: {{ CONFIG_MAP_NAME }}
                key: conjur-version
          - name: CONJUR_APPLIANCE_URL
            valueFrom:
              configMapKeyRef:
                name: {{ CONFIG_MAP_NAME }}
                key: conjur-follower-url
          - name: CONJUR_ACCOUNT
            valueFrom:
              configMapKeyRef:
                name: {{ CONFIG_MAP_NAME }}
                key: conjur-account
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: {{ CONFIG_MAP_NAME }}
                key: follower-certificate

        # values from app config map
          - name: CONJUR_AUTHN_URL
            valueFrom:
              configMapKeyRef:
                name: {{ APP_CONFIG_MAP_NAME }}
                key: conjur-authn-url
          - name: CONJUR_AUTHN_LOGIN
            valueFrom:
              configMapKeyRef:
                name: {{ APP_CONFIG_MAP_NAME }}
                key: conjur-authn-login-init

        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token

      imagePullSecrets:
        - name: dockerpullsecret
      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory
