#!/bin/bash
set -euo pipefail

source ../config/cluster.config
source ../config/openshift.config
source ../config/utils.sh

oc login -u $OSHIFT_CLUSTER_ADMIN_USERNAME
./0_check_dependencies.sh
./stop
./1_prepare_conjur_namespace.sh
./2_prepare_docker_images.sh
./3_deploy_master.sh
./4_deploy_conjur_followers.sh
./5_configure_master.sh
./6_configure_followers.sh
./7_print_cluster_info.sh
./exec-into-cli.sh
