#!/bin/bash
set -euo pipefail

source ../config/cluster.config
source ../config/openshift.config
source ../config/utils.sh

oc login -u $CLUSTER_ADMIN_USERNAME
./0_check_dependencies.sh
./stop
./1_prepare_conjur_namespace.sh

$CLI login -u $FOLLOWER_ADMIN_USERNAME

./2_prepare_docker_images.sh
./3_deploy_master.sh
./4_deploy_conjur_followers.sh
./5_configure_master.sh
./6_configure_followers.sh

./2_init_follower_authn.sh

./7_print_cluster_info.sh
./exec-into-cli.sh
