#!/bin/bash 
#set -eo pipefail

source ../config/cluster.config
source ../config/$PLATFORM.config
source ../config/utils.sh

announce "Deleting Conjur cluster."

$CLI login -u $CLUSTER_ADMIN_USERNAME

set_namespace $FOLLOWER_NAMESPACE_NAME

echo "Untainting nodes."
$CLI adm taint nodes $CONJUR_MASTER_NODE \
	$CONJUR_MASTER_TAINT_KEY:NoSchedule-
$CLI adm taint nodes $CONJUR_FOLLOWER_NODES \
	$CONJUR_FOLLOWER_TAINT_KEY:NoSchedule-

echo "Deleting CLI pod."
$CLI delete --ignore-not-found deploy/conjur-cli

echo "Deleting Master cluster pods."
$CLI delete pod/conjur-master-node --force=true
$CLI delete svc/conjur-master --force=true

echo "Deleting Follower pods."
$CLI delete dc/conjur-follower --force=true
$CLI delete svc/conjur-follower --force=true

echo "Deleting Conjur config map."
$CLI delete --ignore-not-found cm $CONJUR_CONFIG_MAP

echo "Deleting Route to Follower service."
$CLI delete route conjur-follower --force=true

echo "Deleting cluster role."
$CLI delete --ignore-not-found clusterrole conjur-authenticator
$CLI delete --ignore-not-found sa conjur conjur-cluster

echo "Deleting Master route."
conjur_master_route=$($CLI get routes | grep -s conjur-master | awk '{ print $3 }')
$CLI delete --ignore-not-found route $conjur_master_route

echo "Deleting Follower route."
conjur_follower_route=$($CLI get routes | grep -s conjur-follower | awk '{ print $3 }')
$CLI delete --ignore-not-found route $conjur_follower_route

echo "Deleting instantiated deployment yaml."
rm ./deploy-configs/*.yaml

echo "Waiting for Conjur pods to terminate..."
while [[ "$($CLI get pods 2>&1)" != "No resources found." ]]; do
  echo -n '.'
  sleep 3
done 
echo

announce "Cluster deleted."
