#!/bin/bash 
#set -eo pipefail

source ../config/cluster.config
source ../config/openshift.config
source ../config/utils.sh

announce "Deleting Conjur cluster."

set_namespace $FOLLOWER_NAMESPACE_NAME

conjur_appliance_image=$(platform_image "conjur-appliance")

announce "Deleting Master cluster pods."
conjur_cluster_template="./deploy-configs/conjur-master.yaml"
sed -e "s#{{ CONJUR_APPLIANCE_IMAGE }}#$conjur_appliance_image#g" $conjur_cluster_template |
  sed -e "s#{{ IMAGE_PULL_POLICY }}#$IMAGE_PULL_POLICY#g" |
  $CLI delete --ignore-not-found -f -

announce "Deleting Follower cluster pods."
conjur_cluster_template="./deploy-configs/conjur-follower.yaml"
sed -e "s#{{ CONJUR_APPLIANCE_IMAGE }}#$conjur_appliance_image#g" $conjur_cluster_template |
  sed -e "s#{{ IMAGE_PULL_POLICY }}#$IMAGE_PULL_POLICY#g" |
  sed -e "s#{{ CONJUR_FOLLOWER_COUNT }}#$CONJUR_FOLLOWER_COUNT#g" |
  $CLI delete --ignore-not-found -f -

announce "Deleting CLI pod."
$CLI delete --ignore-not-found deploy/conjur-cli

announce "Deleting Master route."
conjur_master_route=$($CLI get routes | grep -s conjur-master | awk '{ print $3 }')
$CLI delete --ignore-not-found route $conjur_master_route

announce "Deleting Follower route."
conjur_follower_route=$($CLI get routes | grep -s conjur-follower | awk '{ print $3 }')
$CLI delete --ignore-not-found route $conjur_follower_route

echo "Waiting for Conjur pods to terminate..."
while [[ "$($CLI get pods 2>&1)" != "No resources found." ]]; do
  echo -n '.'
  sleep 3
done 
echo

echo "Cluster deleted."
